---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: petclinic
  namespace: wego-system
spec:
  interval: 1m0s
  path: ./staging/apps/k8-manifests
  prune: true
  sourceRef:
    kind: GitRepository
    name: petclinic
  validation: client

---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: petclinic
  namespace: wego-system
spec:
  interval: 30s
  ref:
    branch: master
  secretRef:
    name: weave-gitops-arnawseksus-east-1082037726969clustergitops-eks-kf1-dockercon21
  url: ssh://git@github.com/ibuchh/dockercon21.git

