---
apiVersion: wego.weave.works/v1alpha1
kind: Application
metadata:
  labels:
    weave-gitops.weave.works/app-identifier: wego-218d2e17d996e7845b662c7c5cb1e954
  name: petclinic
  namespace: wego-system
spec:
  branch: master
  deployment_type: kustomize
  path: staging/apps/k8-manifests
  source_type: git
  url: ssh://git@github.com/ibuchh/dockercon21.git
