name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  paths:
      - 'staging/apps/k8-manifests/**'

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: prepor/action-aws-iam-authenticator@master

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Build with Maven
      id: maven
      run: |
        mvn -B package 
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Rename tag and push to Docker Hub
      id: build-image
      env:
        VERSION: ${{ github.sha }}
        ECR_REPOSITORY: ibuchh/petclinic-dockercon21
      run: |
        docker tag $ECR_REPOSITORY:0.0.1-SNAPSHOT $ECR_REPOSITORY:$VERSION
        docker push $ECR_REPOSITORY:$VERSION
    - name: Kustomize and push
      id: Kustomize
      env:
        EMAIL: ${{secrets.EMAIL}}
        VERSION: ${{ github.sha }}
        ECR_REPOSITORY: ibuchh/petclinic-dockercon21
      working-directory: ./staging/apps/k8-manifests
      run: |
        kustomize edit set image $ECR_REPOSITORY:$VERSION
        git add .
        git config user.email "$EMAIL"
        git config user.name "Github Action"
        git commit -m "Set dev image tag to short sha"
        git push
