apiVersion: v1
kind: Service
metadata:
  name: petclinic
  namespace: staging
spec:
  type: LoadBalancer
  selector:
    app: petclinic
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80